### ISSUE TITLE
Lunchbox does not compile without DNSSD

### ISSUE THREAD

**Issue by seifertm** [Eyescale/Lunchbox#136]
When trying to compile the git version of Lunchbox (commit e3645e5ef5728401b5d73b3e110cd340fe9a3334), the build exits with the following error:

```
[ 52%] Building CXX object lunchbox/CMakeFiles/Lunchbox.dir/servus.cpp.obj
cd /usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999_build/lunchbox && /usr/bin/x86_64-w64-mingw32-g++  -DBOOST_ALL_NO_LIB -DBOOST_TEST_DYN_LINK -DBoost_NO_BOOST_CMAKE -DCXX_ARRAY_SUPPORTED -DCXX_AUTO_SUPPORTED -DCXX_FINAL_OVERRIDE_SUPPORTED -DCXX_NULLPTR_SUPPORTED -DCXX_SHAREDPTR_SUPPORTED -DCXX_TEMPLATE_ALIAS_SUPPORTED -DCXX_TUPLE_SUPPORTED -DCXX_UNORDERED_MAP_SUPPORTED -DEQ_PLUGIN_BUILD -DHAVE_BYTESWAP_H -DLUNCHBOX_BUILD_DIR=\"/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999_build/\" -DLUNCHBOX_DSO_NAME=\"libLunchbox.dll.3\" -DLUNCHBOX_LITTLEENDIAN -DLUNCHBOX_SHARED -DLUNCHBOX_USE_BOOST=1 -DLUNCHBOX_USE_V1_API=1 -DLUNCHBOX_VERSION=1.9.1 -DLunchbox_EXPORTS -DWARN_DEPRECATED -DWin32=1  -DNDEBUG -O2 -pipe -fomit-frame-pointer  -Wall -Wextra -Winvalid-pch -Winit-self -Wno-unknown-pragmas -Wshadow -fmax-errors=5 -Wnon-virtual-dtor -Wsign-promo -Wvla -fno-strict-aliasing -std=c++11 @CMakeFiles/Lunchbox.dir/includes_CXX.rsp   -o CMakeFiles/Lunchbox.dir/servus.cpp.obj -c /usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999/lunchbox/servus.cpp
/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999/lunchbox/servus.cpp: In member function 'lunchbox::Servus::Result lunchbox::detail::Servus::browse(int32_t)':
/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999/lunchbox/servus.cpp:226:31: error: '_in' was not declared in this scope
/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999/lunchbox/servus.cpp:226:44: error: '_handleEvents' was not declared in this scope
/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999/lunchbox/servus.cpp:227:5: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: *** [lunchbox/CMakeFiles/Lunchbox.dir/servus.cpp.obj] Error 1
make[2]: Leaving directory `/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999_build'
make[1]: *** [lunchbox/CMakeFiles/Lunchbox.dir/all] Error 2
make[1]: Leaving directory `/usr/x86_64-w64-mingw32/tmp/portage/dev-libs/lunchbox-9999/work/lunchbox-9999_build'
make: *** [all] Error 2
```

If I am not mistaken, `_in` and `_handleEvents` are only declared, when LUNCHBOX_USE_DNSSD is set, but they are still referenced outside an `#ifdef` in line 226.

The changes were introduced with commit a90a2da640a35b07f83f7917fcf88268bb1e1657. Reverting this commit makes Lunchbox compile without errors.
